---
# diagrams.net (formerly draw.io) is free online diagram software. You can use it as a flowchart maker, network diagram software, etc
# TODO: Check port 8443 or 8080? Check healthcheck? Check additional servers and image export?
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  drawio-fonts:
  drawio-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  image-export-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  plantuml-server-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  drawio:
    image: jgraph/drawio:${DRAWIO_VERSION}
    container_name: drawio
    restart: ${RESTART_POLICY}
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://plantuml-server:8080/
      - EXPORT_URL=http://image-export:8000/
      - DRAWIO_BASE_URL=${DRAWIO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
#      - DRAWIO_CACHE_DOMAIN=${DRAWIO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
    volumes:
      - drawio-fonts:/usr/share/fonts/drawio
      - drawio-log:/var/log
    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://${DRAWIO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}:8080 || exit 1"]
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.services.drawio-https.loadbalancer.server.port=8080  # or 8443
      - traefik.http.routers.drawio-https.entrypoints=https
      - traefik.http.routers.drawio-https.rule=Host(`${DRAWIO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.drawio-https.tls=true
      - traefik.http.routers.drawio-https.tls.certresolver=myresolver
      - traefik.http.routers.drawio-https.middlewares=authelia@docker
    depends_on:
      - plantuml-server
      - image-export
    networks:
      t2_proxy:
  image-export:
    image: jgraph/export-server
    container_name: image-export
    hostname: image-export
    volumes:
      - drawio-fonts:/usr/share/fonts/drawio
      - image-export-log:/var/log
    environment:
      - DRAWIO_SERVER_URL=${DRAWIO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
  plantuml-server:
    image: jgraph/plantuml-server
    container_name: plantuml-server
    hostname: plantuml-server
    volumes:
      - drawio-fonts:/usr/share/fonts/drawio
      - plantuml-server-log:/var/log
