---
version: "3.8"
# EmbyStat is a personal web server that can calculate all kinds of statistics from your (local) Emby or Jellyfin server. Just install this on your server and let him calculate all kinds of fun stuff. This project is still in Alpha fase, but feel free to pull in on your computer and test it out yourself.
networks:
  t2_proxy:
    external: true
volumes:
  embystat-config:
  embystat-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  embystat:
    image: lscr.io/linuxserver/embystat:${EMBYSTAT_VERSION}
    container_name: embystat
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - embystat-config:/config
      - embystat-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.embystat-https.loadbalancer.server.port=6555
      - traefik.http.routers.embystat-https.entrypoints=https
      - traefik.http.routers.embystat-https.rule=Host(`${EMBYSTAT_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.embystat-https.tls=true
      - traefik.http.routers.embystat-https.tls.certresolver=myresolver
      - traefik.http.routers.embystat-https.middlewares=authelia@docker
    networks:
      t2_proxy:
