---
# Sonarr is a Personal Video Recorder for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID?PUID Variable not set}
      - PGID=${PGID?PGID Variable not set}
      - TZ=${TIMEZONE?TIMEZONE Variable not set}
    volumes:
      - /var/data/sonarr/config:/config
      - /mnt/tv:/tv
      - /mnt/anime:/anime
      - /mnt/downloads:/downloads
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr-https.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr-https.entrypoints=https
      - traefik.http.routers.sonarr-https.rule=Host(`${SONARR_SUB?SONARR_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.http.routers.sonarr-https.tls.certresolver=myresolver
      - traefik.http.routers.sonarr-https.middlewares=authelia@docker
    networks:
      t2_proxy:
