---
version: "3.8"
# Displays movies, shows, music poster for what is currently playing. Displays random (on-demand) titles from multiple Plex libraries. Displays custom pictures, background art, and themes Shows coming soon titles from Sonarr (or Season premieres). Shows coming soon titles from Radarr. Shows coming soon books from Readarr
networks:
  t2_proxy:
    external: true
volumes:
  posterr-config:
  posterr-custom:
  posterr-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  posterr:
    image: petersem/posterr:${POSTERR_VERSION}
    environment:
      TZ: ${TIMEZONE}
      BASEPATH: ""
    volumes:
      - posterr-config:/usr/src/app/config
      - posterr-custom:/usr/src/app/public/custom
      - posterr-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.dashmachine-https.loadbalancer.server.port=3000
      - traefik.http.routers.dashmachine-https.entrypoints=https
      - traefik.http.routers.dashmachine-https.rule=Host(`${POSTERR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.dashmachine-https.tls=true
      - traefik.http.routers.dashmachine-https.tls.certresolver=myresolver
      - traefik.http.routers.dashmachine-https.middlewares=authelia@docker
    networks:
      t2_proxy:
