---
# Kanboard is a free and open source Kanban project management software. Kanban Board. Visualize your work.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  kanboard-app:
  kanboard-plugins:
  kanboard-ssl:
  kanboard-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kanboard-db-data:
  kanboard-db-config:
  kanboard-db-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    volumes:
      - kanboard-app:/var/www/app/data
      - kanboard-plugins:/var/www/app/plugins
      - kanboard-ssl:/etc/nginx/ssl
      - kanboard-log:/var/log
    environment:
      DATABASE_URL: mysql://${KANBOARDDB_USER?KANBOARDDB_USER Variable not set}:${KANBOARDDB_PASS?KANBOARDDB_PASS Variable not set}@kanboard-db/${KANBOARDDB_DB?KANBOARDDB_DB Variable not set}
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.kanboard-https.loadbalancer.server.port=80
      - traefik.http.routers.exkanboardportarr-https.entrypoints=https
      - traefik.http.routers.kanboard-https.rule=Host(`${KANBOARD_SUB?KANBOARD_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.kanboard-https.tls=true
      - traefik.http.routers.kanboard-https.tls.certresolver=myresolver
      - traefik.http.routers.kanboard-https.middlewares=authelia@docker
    networks:
      t2_proxy:
    depends_on:
      - kanboard-db
  kanboard-db:
    image: mariadb:latest
    container_name: kanboard-db
    hostname: kanboard-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${KANBOARDDB_ROOT?KANBOARDDB_ROOT Variable not set}
      MYSQL_DATABASE: ${KANBOARDDB_DB?KANBOARDDB_DB Variable not set}
      MYSQL_USER: ${KANBOARDDB_USER?KANBOARDDB_USER Variable not set}
      MYSQL_PASSWORD: ${KANBOARDDB_PASS?KANBOARDDB_PASS Variable not set}
    volumes:
      - kanboard-db-data:/var/lib/mysql
      - kanboard-db-log:/var/log
      - kanboard-db-config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${KANBOARDDB_ROOT?KANBOARDDB_ROOT variable does not exist}"]
      interval: 10s
      timeout: 5s
      retries: 5
