---
# TODO: Environment and description. Test DNS. Map ./*.conf to local files.
# What is FTLCONF_REPLY_ADDR4 for?
version: "3.8"
networks:
  t2_proxy:
    external:
  pihole:
    driver: macvlan
    driver_opts:
      parent: ${MAIN_NETWORK_ADAPTER}
    ipam:
      config:
        subnet: ${MAIN_SUBNET}
        gateway: ${MAIN_GATEWAY}
        ip_range: ${ALLOCATE_SUBNET}
volumes:
  pihole1-data:
  pihole2-data:
  pihole1-logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pihole2-logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  pihole-one:
    container_name: pihole-one
    image: pihole/pihole:${PIHOLE_ONE_VERSION}
    hostname: pihole-one
#    mac_address: ae:12:67:c4:92:ca
#     cap_add: # Uncomment if you want to use Pi-Hole for DHCP
#       - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
#       - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
#    environment:
#      - FTLCONF_REPLY_ADDR4=192.168.1.5
      - WEBPASSWORD=${PIHOLE_ONE_WEBPASSWORD}
      - PIHOLE_DNS_=pihole-unbound
    volumes:
      - pihole1-data:/etc/pihole:rw
      - /etc/hosts:/etc/hosts:ro
      - ./resolv.conf:/etc/resolv.conf:ro
      - ./dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - ./pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
      - pihole1-logs:/var/log
    networks:
      pihole:
        ipv4_address: ${PIHOLE_ONE_IP}
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole-one-https.loadbalancer.server.port=9117
      - traefik.http.routers.pihole-one-https.entrypoints=https
      - traefik.http.routers.pihole-one-https.rule=Host(`${PIHOLE_ONE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.pihole-one-https.tls=true
      - traefik.http.routers.pihole-one-https.tls.certresolver=myresolver
      - traefik.http.routers.pihole-one-https.middlewares=authelia@docker
  pihole-two:
    container_name: pihole-two
    image: pihole/pihole:${PIHOLE_TWO_VERSION}
    hostname: pihole-two
#    mac_address: e8:1e:01:83:3c:3d
#     cap_add: # Uncomment if you want to use Pi-Hole for DHCP
#       - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
#       - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
#    environment:
#      - FTLCONF_REPLY_ADDR4=192.168.1.5 #PIHOLEUNBOUND_IP?
      - WEBPASSWORD=${PIHOLE_TWO_WEBPASSWORD}
      - PIHOLE_DNS_=pihole-unbound
    volumes:
      - pihole2-data:/etc/pihole
      - /etc/hosts:/etc/hosts:ro
      - ./resolv.conf:/etc/resolv.conf:ro
      - ./dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - ./pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
      - pihole2-logs:/var/log
    networks:
      pihole:
        ipv4_address: ${PIHOLE_TWO_IP}
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole-two-https.loadbalancer.server.port=9117
      - traefik.http.routers.pihole-two-https.entrypoints=https
      - traefik.http.routers.pihole-two-https.rule=Host(`${PIHOLE_TWO_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.pihole-two-https.tls=true
      - traefik.http.routers.pihole-two-https.tls.certresolver=myresolver
      - traefik.http.routers.pihole-two-https.middlewares=authelia@docker
  pihole-unbound:
    container_name: pihole-unbound
    image: mvance/unbound:${PIHOLE_UNBOUND_VERSION}
    hostname: pihole-unbound
#    mac_address: 97:3b:2d:0b:84:d5
    ports:
      - 53/tcp
      - 53/udp
    networks:
      pihole:
        ipv4_address: ${PIHOLE_UNBOUND_IP}
    restart: ${RESTART_POLICY}
