---
# Htpcmanager is a front end for many htpc related applications.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  htpcmanager-config:
  htpcmanager-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  htpcmanager:
    image: lscr.io/linuxserver/htpcmanager:${HTPCMANAGER_VERSION}
    container_name: htpcmanager
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - htpcmanager-config:/config
      - htpcmanager-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.htpcmanager-https.loadbalancer.server.port=8085
      - traefik.http.routers.htpcmanager-https.entrypoints=https
      - traefik.http.routers.htpcmanager-https.rule=Host(`${HTPCMANAGER_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.htpcmanager-https.tls=true
      - traefik.http.routers.htpcmanager-https.tls.certresolver=myresolver
      - traefik.http.routers.htpcmanager-https.middlewares=authelia@docker
    networks:
      t2_proxy:
