---
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  htpcmanager:
#Htpcmanager is a front end for many htpc related applications.
    image: lscr.io/linuxserver/htpcmanager
    container_name: htpcmanager
    environment:
      - PUID=${PUID?PUID Variable not set}
      - PGID=${PGID?PGID Variable not set}
      - TZ=${TIMEZONE?TIMEZONE Variable not set}
    volumes:
      - /var/data/htpcmanager/config:/config
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.htpcmanager-https.loadbalancer.server.port=8085
      - traefik.http.routers.htpcmanager-https.entrypoints=https
      - traefik.http.routers.htpcmanager-https.rule=Host(`${HTPCMANAGER_SUB?HTPCMANAGER_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.htpcmanager-https.tls=true
      - traefik.http.routers.htpcmanager-https.tls.certresolver=myresolver
      - traefik.http.routers.htpcmanager-https.middlewares=authelia@docker
    networks:
      t2_proxy: