---
# Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  overseerr-config:
  overseerr-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:${OVERSEER_VERSION}
    container_name: overseerr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - overseerr-config:/config
      - overseer-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.overseerr-https.loadbalancer.server.port=5055
      - traefik.http.routers.overseerr-https.entrypoints=https
      - traefik.http.routers.overseerr-https.rule=Host(`${OVERSEERR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.overseerr-https.tls=true
      - traefik.http.routers.overseerr-https.tls.certresolver=myresolver
      - traefik.http.routers.overseerr-https.middlewares=authelia@docker
    networks:
      t2_proxy:
