---
version: "3.7"
networks:
  t2_proxy:
    external: true
services:
  emulatorjs:
#Self-hosted Javascript emulation for various system.
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulatorjs
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
    volumes:
      - /var/data/emulatorjs/config:/config
      - /mnt/emulation:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.emulatorjs-backend-https.loadbalancer.server.port=3000
      - traefik.http.routers.emulatorjs-backend-https.entrypoints=https
      - traefik.http.routers.emulatorjs-backend-https.rule=Host(`${EMULATORJS_BACKEND_SUB?EMULATORJS_BACKEND_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.emulatorjs-backend-https.tls=true
      - traefik.http.routers.emulatorjs-backend-https.tls.certresolver=myresolver
      - traefik.http.routers.emulatorjs-backend-https.middlewares=authelia@docker
      - traefik.http.services.emulatorjs-https.loadbalancer.server.port=80
      - traefik.http.routers.emulatorjs-https.entrypoints=https
      - traefik.http.routers.emulatorjs-https.rule=Host(`${EMULATORJS_SUB?EMULATORJS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.emulatorjs-https.tls=true
      - traefik.http.routers.emulatorjs-https.tls.certresolver=myresolver
      - traefik.http.routers.emulatorjs-https.middlewares=authelia@docker
    networks:
      - t2_proxy
  openra:
#OpenRA is an open source project that recreates and modernizes classic real time strategy games, like Red Alert, Command & Conquer, and Dune
    image: rmoriz/openra
    container_name: openra
    environment:
      - Name=${OPENRA_SERVERNAME?OPENRA_SERVERNAME Variable not set}
      - Mod=ra
      - ListenPort=1234
      - AdvertiseOnline=false
      - Password=${OPENRA_PASS?OPENRA_PASS Variable not set}
      - EnableSingleplayer=${OPENRA_SINGLE?OPENRA_SINGLE Variable not set}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.openra-https.loadbalancer.server.port=1234 
      - traefik.http.routers.openra-https.entrypoints=https
      - traefik.http.routers.openra-https.rule=Host(`${OPENRA_SUB?OPENRA_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.openra-https.tls=true
      - traefik.http.routers.openra-https.tls.certresolver=myresolver
      - traefik.http.routers.openra-https.middlewares=authelia@docker
    networks:
      - t2_proxy
  supermario:
#Infinite Mario in HTML5 JavaScript - using Canvas and Audio elements
    image: pengbai/docker-supermario
    container_name: supermario
    restart: unless-stopped    
    labels:
      - traefik.enable=true
      - traefik.http.services.supermario-https.loadbalancer.server.port=8080 
      - traefik.http.routers.supermario-https.entrypoints=https
      - traefik.http.routers.supermario-https.rule=Host(`${SUPERMARIO_SUB?SUPERMARIO_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.supermario-https.tls=true
      - traefik.http.routers.supermario-https.tls.certresolver=myresolver
      - traefik.http.routers.supermario-https.middlewares=authelia@docker
    networks:
      - t2_proxy