---
# MovieMatch connects to your Plex server and gets a list of movies (from any libraries marked as a movie library). As many people as you want connect to your MovieMatch server and get a list of shuffled movies. Swipe right to 👍, swipe left to 👎. If two (or more) people swipe right on the same movie, it'll show up in everyone's matches. The movies that the most people swiped right on will show up first.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  moviematch-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  moviematch:
    image: lukechannings/moviematch:${MOVIEMATCH_VERSION}
    container_name: moviematch
    volumes:
      - moviematch-log:/var/log
    environment:
      - PLEX_URL: "${PLEX_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
      - PLEX_TOKEN: "PLEX_TOKEN}"
    labels:
      - traefik.enable=true
      - traefik.http.services.dashmachine-https.loadbalancer.server.port=8000
      - traefik.http.routers.dashmachine-https.entrypoints=https
      - traefik.http.routers.dashmachine-https.rule=Host(`${MOVIEMATCH_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.dashmachine-https.tls=true
      - traefik.http.routers.dashmachine-https.tls.certresolver=myresolver
      - traefik.http.routers.dashmachine-https.middlewares=authelia@docker
    networks:
      t2_proxy:
