---
# WBO is an online collaborative whiteboard that allows many users to draw simultaneously on a large virtual board. The board is updated in real time.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  whiteboard-data:
  whiteboard-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  whiteboard:
    image: lovasoa/wbo:latest
    container_name: whiteboard
    volumes:
      - whiteboard-data:/opt/app/server-data
      - whiteboard-log:/var/log
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.whiteboard-https.loadbalancer.server.port=80
      - traefik.http.routers.whiteboard-https.entrypoints=https
      - traefik.http.routers.whiteboard-https.rule=Host(`${HASTEBIN_SUB?HASTEBIN_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.whiteboard-https.tls=true
      - traefik.http.routers.whiteboard-https.tls.certresolver=myresolver
      - traefik.http.routers.whiteboard-https.middlewares=authelia@docker
    networks:
      t2_proxy:
