---
# Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  audiobookshelf:
    image: advplyr/audiobookshelf
    container_name: audiobookshelf
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    volumes:
      - /var/data/audiobookshelf/config:/config
      - /var/data/audiobookshelf/metadata:/metadata
      - /mnt/audiobooks:/audiobooks
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf-https.loadbalancer.server.port=80
      - traefik.http.routers.audiobookshelf-https.entrypoints=https
      - traefik.http.routers.audiobookshelf-https.rule=Host(`${AUDIOBOOKSHELF_SUB?AUDIOBOOKSHELF_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.audiobookshelf-https.tls=true
      - traefik.http.routers.audiobookshelf-https.tls.certresolver=myresolver
      - traefik.http.routers.audiobookshelf-https.middlewares=authelia@docker
    networks:
      t2_proxy:
