---
# Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  audiobookshelf-config:
  audiobookshelf-metadata:
  audiobookshelf-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  audiobookshelf:
    image: advplyr/audiobookshelf
    container_name: audiobookshelf
    restart: RESTART_POLICY
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
      - audiobookshelf-log:/var/log
      - AUDIOBOOKS_DIRECTORY:/audiobooks
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf-https.loadbalancer.server.port=80
      - traefik.http.routers.audiobookshelf-https.entrypoints=https
      - traefik.http.routers.audiobookshelf-https.rule=Host(`AUDIOBOOKSHELF_SUBDOMAIN.CLOUDFLARE_DOMAIN`)
      - traefik.http.routers.audiobookshelf-https.tls=true
      - traefik.http.routers.audiobookshelf-https.tls.certresolver=myresolver
      - traefik.http.routers.audiobookshelf-https.middlewares=authelia@docker
    networks:
      t2_proxy:
