---
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  heimdall:
#Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way. Simplicity is the key
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID?PUID Variable not set}
      - PGID=${PGID?PGID Variable not set}
      - TZ=${TIMEZONE?TIMEZONE Variable not set}
    volumes:
      - /var/data/heimdall/config:/config
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.heimdall-https.loadbalancer.server.port=80
      - traefik.http.routers.heimdall-https.entrypoints=https
      - traefik.http.routers.heimdall-https.rule=Host(`${HEIMDALL_SUB?HEIMDALL_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.heimdall-https.tls=true
      - traefik.http.routers.heimdall-https.tls.certresolver=myresolver
      - traefik.http.routers.heimdall-https.middlewares=authelia@docker
    networks:
      t2_proxy: