---
# COPS links to your Calibre library database and allows downloading and emailing of books directly from a web browser and provides a OPDS feed to connect to your devices.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  cops-config:
  cops-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  cops:
    image: lscr.io/linuxserver/cops:${COPS_VERSION}
    container_name: cops
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - cops-config:/config
      - cops-log:/var/log
      - ${EBOOKS_DIRECTORY}:/books
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.cops-https.loadbalancer.server.port=80
      - traefik.http.routers.cops-https.entrypoints=https
      - traefik.http.routers.cops-https.rule=Host(`${COPS_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.cops-https.tls=true
      - traefik.http.routers.cops-https.tls.certresolver=myresolver
      - traefik.http.routers.cops-https.middlewares=authelia@docker
    networks:
      t2_proxy:
