---
# Plex gives you the power to add, access and share all the entertainment that matters to you, on almost any device.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  plex-config:
  plex-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  plex:
    image: lscr.io/linuxserver/plex:${PLEX_VERSION}
    container_name: plex
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - plex-config:/config
      - plex-log:/var/log
      - ${TV_DIRECTORY}:/tv
      - ${ANIME_DIRECTORY}:/anime
      - ${MOVIES_DIRECTORY}:/movies
      - ${MUSIC_DIRECTORY}:/music
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.plex-https.loadbalancer.server.port=32400
      - traefik.http.routers.plex-https.entrypoints=https
      - traefik.http.routers.plex-https.rule=Host(`${PLEX_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.plex-https.tls=true
      - traefik.http.routers.plex-https.tls.certresolver=myresolver
      - traefik.http.routers.plex-https.middlewares=authelia@docker
    networks:
      t2_proxy:
