---
# ​Muximux is a lightweight portal to view & manage your HTPC apps without having to run anything more than a PHP enabled webserver.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  muximux-config:
  muximux-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  muximux:
    image: lscr.io/linuxserver/muximux:${MUXIMUX_VERSION}
    container_name: muximux
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - muximux-config:/config
      - muximux-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.muximux-https.loadbalancer.server.port=80
      - traefik.http.routers.muximux-https.entrypoints=https
      - traefik.http.routers.muximux-https.rule=Host(`${MUXIMUX_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.muximux-https.tls=true
      - traefik.http.routers.muximux-https.tls.certresolver=myresolver
      - traefik.http.routers.muximux-https.middlewares=authelia@docker
    networks:
      t2_proxy:
