---
# Flame is self-hosted startpage for your server. Its design is inspired (heavily) by SUI. Flame is very easy to setup and use. With built-in editor
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  flame-data:
  flame-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  flame:
    image: pawelmalak/flame:${FLAME_VERSION}
    container_name: flame
    volumes:
      - flame-data:/app/data
      - flame-log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.flame-https.loadbalancer.server.port=5005
      - traefik.http.routers.flame-https.entrypoints=https
      - traefik.http.routers.flame-https.rule=Host(`${FLAME_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.flame-https.tls=true
      - traefik.http.routers.flame-https.tls.certresolver=myresolver
      - traefik.http.routers.flame-https.middlewares=authelia@docker
    networks:
      t2_proxy:
