---
# Komga is a free and open source comics/mangas server. Chat on Discord. Features. Browse libraries, series and books via a responsive web UI
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  komga-config:
  komga-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - komga-config:/config
      - /mnt/manga:/data/manga
      - /mnt/comics:/data/comics
      - /etc/timezone:/etc/timezone:ro
      - komga-log:/var/log
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.komga-https.loadbalancer.server.port=8080
      - traefik.http.routers.komga-https.entrypoints=https
      - traefik.http.routers.komga-https.rule=Host(`${KOMGA_SUB?KOMGA_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.komga-https.tls=true
      - traefik.http.routers.komga-https.tls.certresolver=myresolver
      - traefik.http.routers.komga-https.middlewares=authelia@docker
    networks:
      t2_proxy:
