---
# Bookstack is a free and open source Wiki designed for creating beautiful documentation. Featuring a simple, but powerful WYSIWYG editor
# Includes app and MariaDB
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  bookstack-config:
  bookstack-db-config:
  bookstack-db-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  bookstack-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:${BOOKSTACK_VERSION}
    container_name: bookstack
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - APP_URL=https://${BOOKSTACK_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
      - DB_HOST=bookstack-db
      - DB_USER=${BOOKSTACK_MYSQL_USER}
      - DB_PASS=${BOOKSTACK_MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack-config:/config
      - bookstack-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.bookstack-https.loadbalancer.server.port=80
      - traefik.http.routers.bookstack-https.entrypoints=https
      - traefik.http.routers.bookstack-https.rule=Host(`${BOOKSTACK_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.bookstack-https.tls=true
      - traefik.http.routers.bookstack-https.tls.certresolver=myresolver
      - traefik.http.routers.bookstack-https.middlewares=authelia@docker
    depends_on:
      - bookstack-db
    networks:
      t2_proxy:
  bookstack-db:
    image: lscr.io/linuxserver/mariadb:${BOOKSTACK_MARIADB_VERSION}
    container_name: bookstack-db
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${BOOKSTACK_MYSQL_DATABASE}
      - MYSQL_USER=${BOOKSTACK_MYSQL_USER}
      - MYSQL_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${BOOKSTACK_MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - bookstack-db-config:/config
      - bookstack-db-log:/var/log
    restart: ${RESTART_POLICY}
