---
# ownCloud, your collaboration tool · Filesharing, trusted by 200 million users worldwide · For organizations with high data governance requirements
# Includes: App, MariaDB, and Redis
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  owncloud-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  owncloud-mariadb-data:
  owncloud-mariadb-conf:
  owncloud-mariadb-log:
      driver_opts:
      type: tmpfs
      device: tmpfs
  owncloud-redis-data:
services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud
    restart: ${RESTART_POLICY}
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_MYSQL_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_MYSQL_PASSWORD}
      - OWNCLOUD_DB_HOST=owncloud-mariadb
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud-redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/owncloud:/mnt/data
    labels:
      - traefik.enable=true
      - traefik.http.services.owncloud-https.loadbalancer.server.port=8080
      - traefik.http.routers.owncloud-https.entrypoints=https
      - traefik.http.routers.owncloud-https.rule=Host(`${OWNCLOUD_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.owncloud-https.tls=true
      - traefik.http.routers.owncloud-https.tls.certresolver=myresolver
      - traefik.http.routers.owncloud-https.middlewares=authelia@docker
    networks:
      t2_proxy:
    depends_on:
      - owncloud-mariadb
      - owncloud-redis
  owncloud-mariadb:
    image: mariadb:${OWNCLOUD_MYSQL_VERSION}
    container_name: owncloud-mariadb
    hostname: owncloud-mariadb
    restart: ${RESTART_POLICY}
    environment:
      - MYSQL_ROOT_PASSWORD=${OWNCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${OWNCLOUD_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${OWNCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${OWNCLOUD_MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud-mysql-data:/var/lib/mysql
      - owncloud-mysql-config:/etc/mysql
      - owncloud-mysql-log:/var/log
  owncloud-redis:
    image: redis:${OWNCLOUD_REDIS_VERSION}
    container_name: owncloud-redis
    hostname: owncloud-redis
    restart: ${RESTART_POLICY}
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud-redis-data:/data
