---
# Search your movies and find missing movies from MovieDB collections.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  gaps-data:
  gaps-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  gaps:
    image: housewrecker/gaps:latest  # housewrecker/gaps:arm-latest for pi
    container_name: gaps
    volumes:
      - gaps-data:/gaps
      - gaps-log:/var/log
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.gaps-https.loadbalancer.server.port=5000
      - traefik.http.routers.gaps-https.entrypoints=https
      - traefik.http.routers.gaps-https.rule=Host(`${GAPS_SUB?GAPS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.gaps-https.tls=true
      - traefik.http.routers.gaps-https.tls.certresolver=myresolver
      - traefik.http.routers.gaps-https.middlewares=authelia@docker
    networks:
      t2_proxy:
