---
# Gitea - Git with a cup of tea · A painless self-hosted Git service. 
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  gitea:
    image: gitea/gitea:1.16.4
    container_name: gitea
    environment:
      - USER_UID=0
      - USER_GID=0
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=${GITEADB_DB?GITEADB_DB Variable not set}
      - GITEA__database__USER=${GITEADB_USER?GITEADB_USER Variable not set}
      - GITEA__database__PASSWD=${GITEADB_PASS?GITEADB_PASS Variable not set}
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    volumes:
      - /var/data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_SSHPORT?GITEA_SSHPORT Variable not set}:22
    labels:
      - traefik.enable=true
      - traefik.http.services.gitea-https.loadbalancer.server.port=3000
      - traefik.http.routers.gitea-https.entrypoints=https
      - traefik.http.routers.gitea-https.rule=Host(`${GITEA_SUB?GITEA_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.gitea-https.tls=true
      - traefik.http.routers.gitea-https.tls.certresolver=myresolver
      - traefik.http.routers.gitea-https.middlewares=authelia@docker
    depends_on:
      - gitea-db
    networks:
      t2_proxy:
  gitea-db:
    image: mysql:8
    container_name: gitea-db
    hostname: gitea-db
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    environment:
      - MYSQL_ROOT_PASSWORD=${GITEADB_ROOTPASS?GITEADB_ROOTPASS Variable not set}
      - MYSQL_USER=${GITEADB_USER?GITEADB_USER Variable not set}
      - MYSQL_PASSWORD=${GITEADB_PASS?GITEADB_PASS Variable not set}
      - MYSQL_DATABASE=${GITEADB_DB?GITEADB_DB Variable not set}
    volumes:
      - /var/data/gitea/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${GITEADB_ROOTPASS?GITEADB_ROOTPASS variable does not exist}"]
      interval: 10s
      timeout: 5s
      retries: 5
