---
# Bringing all of your home videos, music, and photos together into one place has never been easier
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  emby-config:
  emby-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  emby:
    image: lscr.io/linuxserver/emby:${EMBY_VERSION}
    container_name: emby
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - emby-config:/config
      - emby-log:/var/log
      - ${TV_DIRECTORY}:/data/tvshows
      - ${MOVIES_DIRECTORY}:/data/movies
      - ${ANIME_DIRECTORY}:/data/anime
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.emby-https.loadbalancer.server.port=8096
      - traefik.http.routers.emby-https.entrypoints=https
      - traefik.http.routers.emby-https.rule=Host(`${EMBY_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.emby-https.tls=true
      - traefik.http.routers.emby-https.tls.certresolver=myresolver
      - traefik.http.routers.emby-https.middlewares=authelia@docker
    networks:
      t2_proxy:
