---
# MagicMirror² is an open source modular smart mirror platform. With a growing list of installable modules, the MagicMirror² allows you to convert your hallway or bathroom mirror into your personal assistant.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  magicmirror-config:
  magicmirror-modules:
  magicmirror-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  magicmirror:
    container_name: magicmirror
    image: bastilimbach/docker-magicmirror:${MAGICMIRROR_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - magicmirror-config:/opt/magic_mirror/config
      - magicmirror-modules:/opt/magic_mirror/modules
      - magicmirror-log:/var/log
    labels:
      - traefik.enable=true
      - traefik.http.services.magicmirror-https.loadbalancer.server.port=8080
      - traefik.http.routers.magicmirror-https.entrypoints=https
      - traefik.http.routers.magicmirror-https.rule=Host(`${MAGICMIRROR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.magicmirror-https.tls=true
      - traefik.http.routers.magicmirror-https.tls.certresolver=myresolver
      - traefik.http.routers.magicmirror-https.middlewares=authelia@docker
    networks:
      t2_proxy:
