---
#LanguageTool is an Open Source proofreading software for English, French, German, Polish, Russian, and more than 20 other languages. 
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    environment:
        - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
        - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
        - Java_Xmx=1g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
        - /var/data/ngrams/data:/ngrams
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.languagetool-https.loadbalancer.server.port=8010
      - traefik.http.routers.languagetool-https.entrypoints=https
      - traefik.http.routers.languagetool-https.rule=Host(`${LANGUAGETOOL_SUB?LANGUAGETOOL_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.languagetool-https.tls=true
      - traefik.http.routers.languagetool-https.tls.certresolver=myresolver
      - traefik.http.routers.languagetool-https.middlewares=authelia@docker
    networks:
      t2_proxy: