---
# Python web ui to download videos from YouTube and add metadata on top of it.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  metatube-data:
  metatube-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  metatube:
    restart: always
    image: jvt038/metatube:latest
    container_name: metatube
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - /mnt/downloads:/downloads
      - metatube-data:/database
      - metatube-log:/var/log
    labels:
      - traefik.enable=true
      - traefik.http.services.metatube-https.loadbalancer.server.port=5000
      - traefik.http.routers.metatube-https.entrypoints=https
      - traefik.http.routers.metatube-https.rule=Host(`${METATUBE_SUB?METATUBE_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.metatube-https.tls=true
      - traefik.http.routers.metatube-https.tls.certresolver=myresolver
      - traefik.http.routers.metatube-https.middlewares=authelia@docker
    networks:
      t2_proxy:
