---
# Allows you to share your Radarr lists with others, without having to give them your Radarr API key.
# TO DO: Check build stuff https://github.com/petersem/exportarr
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  exportarr-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  exportarr:
    image: petersem/exportarr:${EXPORTARR_VERSION}
    container_name: exportarr
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      TOKEN: ${EXPORTARR_TOKEN}
      RADARR_URL: "http://${RADARR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}"
      RADARR_TOKEN: ${RADARR_TOKEN}
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    volumes:
      - exportarr-log:/var/log
    labels:
      - traefik.enable=true
      - traefik.http.services.exportarr-https.loadbalancer.server.port=3000
      - traefik.http.routers.exportarr-https.entrypoints=https
      - traefik.http.routers.exportarr-https.rule=Host(`${EXPORTARR_SUB?EXPORTARR_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.exportarr-https.tls=true
      - traefik.http.routers.exportarr-https.tls.certresolver=myresolver
      - traefik.http.routers.exportarr-https.middlewares=authelia@docker
    networks:
      t2_proxy:
