---
# Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar3, Lidarr, DuckieTV, qBittorrent, Nefarious etc.) into tracker-site-specific http queries, parses the html or json response, and then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  jackett-config:
  jackett-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  jackett:
    image: lscr.io/linuxserver/jackett:${JACKETT_VERSION}
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true
    volumes:
      - jackett-config:/config
      - jackett-log:/var/log
      - ${DOWNLOAD_DIRECTORY}:/downloads
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.jackett-https.loadbalancer.server.port=9117
      - traefik.http.routers.jackett-https.entrypoints=https
      - traefik.http.routers.jackett-https.rule=Host(`${JACKETT_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.jackett-https.tls=true
      - traefik.http.routers.jackett-https.tls.certresolver=myresolver
      - traefik.http.routers.jackett-https.middlewares=authelia@docker
    networks:
      t2_proxy:
