---
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  linkding:
#linkding is a simple bookmark service that you can host yourself. It's designed be to be minimal, fast and easy to set up using Docker
    image: sissbruecker/linkding:latest
    container_name: linkding
    volumes:
      - /var/data/linkding/data:/etc/linkding/data
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.linkding-https.loadbalancer.server.port=80 
      - traefik.http.routers.linkding-https.entrypoints=https
      - traefik.http.routers.linkding-https.rule=Host(`${LINKDING_SUB?LINKDING_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.linkding-https.tls=true
      - traefik.http.routers.linkding-https.tls.certresolver=myresolver
      - traefik.http.routers.linkding-https.middlewares=authelia@docker
    networks:
      t2_proxy: