---
#
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  babybuddy-config:
  babybuddy-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:${BABYBUDDY_VERSION}
    container_name: babybuddy
    environment:
      - TZ=${TIMEZONE}
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://${BABYBUDDY_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
    volumes:
      - babybuddy-config:/config
      - babybuddy-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.babybuddy-https.loadbalancer.server.port=8000
      - traefik.http.routers.babybuddy-https.entrypoints=https
      - traefik.http.routers.babybuddy-https.rule=Host(`${BABYBUDDY_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.babybuddy-https.tls=true
      - traefik.http.routers.babybuddy-https.tls.certresolver=myresolver
      - traefik.http.routers.babybuddy-https.middlewares=authelia@docker
    networks:
      t2_proxy:
