---
version: "3.8"
# YoutubeDL-Material is a Material Design frontend for youtube-dl. It's coded using Angular 9 for the frontend, and Node.js on the backend.
networks:
  t2_proxy:
    external: true
volumes:
  youtubedl-data:
  youtubedl-subscriptions:
  youtubedl-users:
  youtubedl-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  youtubedl:
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
    volumes:
      - youtubedl-data:/app/appdata
      - /mnt/downloads/youtubedl/audio:/app/audio
      - /mnt/downloads/youtubedl/video:/app/video
      - youtubedl-subscriptions:/app/subscriptions
      - youtubedl-users:/app/users
      - youtubedl-log:/var/log
    image: tzahi12345/youtubedl-material:latest
    container_name: youtube-dl
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.youtubedl-https.loadbalancer.server.port=22300
      - traefik.http.routers.youtubedl-https.entrypoints=https
      - traefik.http.routers.youtubedl-https.rule=Host(`${WORDPRESS_SUB?WORDPRESS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.youtubedl-https.tls=true
      - traefik.http.routers.youtubedl-https.tls.certresolver=myresolver
      - traefik.http.routers.youtubedl-https.middlewares=authelia@docker
    networks:
      t2_proxy:
