---
# Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No Flash, No Java, No Websocket,
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  librespeed-config:
  librespeed-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  librespeed-db-data:
  librespeed-db-config:
  librespeed-db-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:${LIBRESPEED_VERSION}
    container_name: librespeed
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - PASSWORD=${LIBRESPEED_PASSWORD}
      - CUSTOM_RESULTS=false
      - DB_TYPE=mysql
      - DB_HOSTNAME=librespeed-db
      - DB_NAME=${LIBRESPEEDDB_DB}
      - DB_USERNAME=${LIBRESPEEDDB_USER}
      - DB_PASSWORD=${LIBRESPEEDDB_PASS}
      - DB_PORT=3306
    volumes:
      - librespeed-config:/config
      - librespeed-log:/var/log
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.exportarr-https.loadbalancer.server.port=80
      - traefik.http.routers.exportarr-https.entrypoints=https
      - traefik.http.routers.exportarr-https.rule=Host(`${LIBRESPEED_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.exportarr-https.tls=true
      - traefik.http.routers.exportarr-https.tls.certresolver=myresolver
      - traefik.http.routers.exportarr-https.middlewares=authelia@docker
    networks:
      t2_proxy:
    depends_on:
      - librespeed-db
  librespeed-db:
    image: mariadb:${LIBRESPEEDDB_VERSION}
    container_name: librespeed-db
    hostname: librespeed-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${LIBRESPEEDDB_ROOT}
      MYSQL_DATABASE: ${LIBRESPEEDDB_DB}
      MYSQL_USER: ${LIBRESPEEDDB_USER}
      MYSQL_PASSWORD: ${LIBRESPEEDDB_PASS}
    volumes:
      - librespeed-db-data:/var/lib/mysql
      - librespeed-db-log:/var/log
      - librespeed-db-config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${LIBRESPEEDDB_ROOT}"]
      interval: 10s
      timeout: 5s
      retries: 5
