# TODO: Everything!
# https://prometheus.io/docs/guides/cadvisor/
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
