version: "3.7"
networks:
  t2_proxy:
    external: true
services:
  audiobookshelf:
#Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks
    image: advplyr/audiobookshelf
    container_name: audiobookshelf
    restart: unless-stopped
    volumes:
      - /var/data/audiobookshelf/config:/config
      - /var/data/audiobookshelf/metadata:/metadata
      - /mnt/audiobooks:/audiobooks
    labels:
      - traefik.enable=true
      - traefik.http.services.audiobookshelf-https.loadbalancer.server.port=80
      - traefik.http.routers.audiobookshelf-https.entrypoints=https
      - traefik.http.routers.audiobookshelf-https.rule=Host(`${KUMA_SUB?KUMA_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.audiobookshelf-https.tls=true
      - traefik.http.routers.audiobookshelf-https.tls.certresolver=myresolver
      - traefik.http.routers.audiobookshelf-https.middlewares=authelia@docker
    networks:
      - t2_proxy
  booksonic-air:
#Booksonic Air - A server for streaming your audiobooks, successor to the original Booksonic server. Based on Airsonic. 
    image: lscr.io/linuxserver/booksonic-air
    container_name: booksonic-air
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - CONTEXT_PATH=${BOOKSONIC_SUB?BOOKSONIC_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}
    volumes:
      - /var/data/booksonic/config:/config
      - /mnt/audiobooks:/audiobooks
      - /mnt/podcasts:/podcasts
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.booksonic-https.loadbalancer.server.port=4040
      - traefik.http.routers.booksonic-https.entrypoints=https
      - traefik.http.routers.booksonic-https.rule=Host(`${BOOKSONIC_SUB?BOOKSONIC_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.booksonic-https.tls=true
      - traefik.http.routers.booksonic-https.tls.certresolver=myresolver
      - traefik.http.routers.booksonic-https.middlewares=authelia@docker
    networks:
      - t2_proxy