---
# https://github.com/bakito/adguardhome-sync
# Synchronize AdGuardHome config to a replica instance.
version: "3.8"
networks:
  t2_proxy:
    external:
  smarthome:
    driver: macvlan
    driver_opts:
      parent: MAIN_NETWORK_ADAPTER
    ipam:
      config:
        subnet: MAIN_SUBNET
        gateway: GATEWAY
        ip_range: ALLOCATE_SUBNET
volumes:
  adguardhome-one-work:
  adguardhome-one-config:
  adguardhome-one-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  adguardhome-two-work:
  adguardhome-two-config:
  adguardhome-two-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  adguardhome-sync-config:
  adguardhome-sync-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  adguardhome-one:
    image: adguard/adguardhome
    container_name: adguardhome-one
    hostname: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - adguardhome-one-work:/opt/adguardhome/work
      - adguardhome-one-config:/opt/adguardhome/conf
      - adguardhome-one-log:/var/log
    restart: RESTART_POLICY
    labels:
      - traefik.enable=true
      - traefik.http.services.adguardhome-one-https.loadbalancer.server.port=443
      - traefik.http.routers.adguardhome-one-https.entrypoints=https
      - traefik.http.routers.adguardhome-one-https.rule=Host(`SUBDOMAIN_ONE.CLOUDFLARE_DOMAIN`)
      - traefik.http.routers.adguardhome-one-https.tls=true
      - traefik.http.routers.adguardhome-one-https.tls.certresolver=myresolver
    networks:
      smarthome:
        - ipv4_address: IP_ONE
      t2_proxy:
  adguardhome-two:
    image: adguard/adguardhome
    container_name: adguardhome-two
    hostname: adguardhome-two
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - adguardhome-two-work :/opt/adguardhome/work
      - adguardhome-two-config:/opt/adguardhome/conf
      - adguardhome-two-log:/var/log
    restart: RESTART_POLICY
    networks:
      smarthome:
        ipv4_address: IP_TWO
      t2_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.services.adguardhome-two-https.loadbalancer.server.port=443
      - traefik.http.routers.adguardhome-two-https.entrypoints=https
      - traefik.http.routers.adguardhome-two-https.rule=Host(`SUBDOMAIN_TWO.CLOUDFLARE_DOMAIN`)
      - traefik.http.routers.adguardhome-two-https.tls=true
      - traefik.http.routers.adguardhome-two-https.tls.certresolver=myresolver
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=USER_ID
      - PGID=GROUP_ID
      - TZ=TIMEZONE
      - CONFIGFILE=/config/adguardhome-sync.yaml
    volumes:
      - adguardhome-sync-config:/config
      - adguardhome-sync-log:/var/log
    ports:
      - ADGUARDHOME_SYNC_PORT:8080
    restart: RESTART_POLICY
