---
# https://github.com/bakito/adguardhome-sync
# Synchronize AdGuardHome config to a replica instance.
version: "3.8"
networks:
  t2_proxy:
    external:
services:
  smarthome:
    driver: macvlan
    driver_opts:
      parent: ${ETHERNET_PORT?ETHERNET_PORT Variable not set}
    ipam:
      config:
        subnet: ${SUBNET_IP?SUBNET_IP Variable not set}
        gateway: ${GATEWAY_IP?GATEWAY_IP Variable not set}
        ip_range: ${SUBNET_RANGE?SUBNET_RANGE Variable not set}
  adguardhome-one:
    image: adguard/adguardhome
    container_name: adguardhome-one
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /var/data/adguardhome/work:/opt/adguardhome/work
      - /var/data/adguardhome/config:/opt/adguardhome/conf
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    networks:
      smarthome:
        - ipv4_address: ${ADGUARDHOME_ONE_IP?ADGUARDHOME_ONE_IP Variable not set}
      t2_proxy:
  adguardhome-two:
    image: adguard/adguardhome
    container_name: adguardhome-two
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /var/data/adguardhome2/work :/opt/adguardhome/work
      - /var/data/adguardhome2/config:/opt/adguardhome/conf
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    networks:
      smarthome:
        ipv4_address: ${ADGUARDHOME_TWO_IP?ADGUARDHOME_TWO_IP Variable not set}
      t2_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.services.adguardhome-one-https.loadbalancer.server.port=443
      - traefik.http.routers.adguardhome-one-https.entrypoints=https
      - traefik.http.routers.adguardhome-one-https.rule=Host(`${ADGUARDHOME_TWO_SUB?ADGUARDHOME_TWO_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.adguardhome-one-https.tls=true
      - traefik.http.routers.adguardhome-one-https.tls.certresolver=myresolver
      - traefik.http.routers.adguardhome-one-https.middlewares=authelia@docker
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=${PUID?PUID Variable not set}
      - PGID=${PGID?PGID Variable not set}
      - TZ=${TIMEZONE?TIMEZONE Variable not set}
      - CONFIGFILE=/config/adguardhome-sync.yaml  # optional
    volumes:
      - /var/data/adguardhome-sync/config:/config
    ports:
      - 8080:8080
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
