---
# Torrent Client
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  deluge-config:
  deluge-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  deluge:
    image: lscr.io/linuxserver/deluge:${DELUGE_VERSION}
    container_name: deluge
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - DELUGE_LOGLEVEL=${DELUGE_LOG_LEVEL}  # optional "error"
    volumes:
      - deluge/config:/config
      - deluge-log:/var/log
      - ${DOWNLOADS_DIRECTORY}:/downloads
    ports:
      - ${DELUGE_PORT}:6881
      - ${DELUGE_PORT}:6881/udp
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.deluge-https.loadbalancer.server.port=8112
      - traefik.http.routers.deluge-https.entrypoints=https
      - traefik.http.routers.deluge-https.rule=Host(`${DELUGE_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.deluge-https.tls=true
      - traefik.http.routers.deluge-https.tls.certresolver=myresolver
      - traefik.http.routers.deluge-https.middlewares=authelia@docker
    networks:
      t2_proxy:
