---
# Jellyfin is the volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  jellyfin-config:
  jellyfin-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
    volumes:
      - jellyfin-config:/config
      - jellyfin-log:/var/log
      - /mnt/tv:/data/tvshows
      - /mnt/movies:/data/movies
      - /mnt/anime:/data/anime
    ports:
      - 7359:7359/udp  # Local jellyfin server discovery
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.jellyfin-https.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin-https.entrypoints=https
      - traefik.http.routers.jellyfin-https.rule=Host(`${JELLYFIN_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.jellyfin-https.tls=true
      - traefik.http.routers.jellyfin-https.tls.certresolver=myresolver
      - traefik.http.routers.jellyfin-https.middlewares=authelia@docker
    networks:
      t2_proxy:
