---
# Booksonic Air - A server for streaming your audiobooks, successor to the original Booksonic server. Based on Airsonic. 
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  booksonic-config:
  booksonic-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  booksonic-air:
    image: lscr.io/linuxserver/booksonic-air:${BOOKSONIC_VERSION}
    container_name: booksonic-air
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - CONTEXT_PATH=${BOOKSONIC_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
    volumes:
      - booksonic-config:/config
      - booksonic-log:/var/log
      - /mnt/audiobooks:/audiobooks
      - /mnt/podcasts:/podcasts
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.booksonic-https.loadbalancer.server.port=4040
      - traefik.http.routers.booksonic-https.entrypoints=https
      - traefik.http.routers.booksonic-https.rule=Host(`${BOOKSONIC_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.booksonic-https.tls=true
      - traefik.http.routers.booksonic-https.tls.certresolver=myresolver
      - traefik.http.routers.booksonic-https.middlewares=authelia@docker
    networks:
      t2_proxy:
