---
# Portainer is a self-service container service delivery platform. It is the definitive container management GUI for Kubernetes, Docker and Swarm.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  portainer-data:
  portainer-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer-data:/data
      - portainer-log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer-https.loadbalancer.server.port=9443
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.rule=Host(`${PORTAINER_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.tls.certresolver=myresolver
      - traefik.http.routers.portainer-https.middlewares=authelia@docker
    networks:
      t2_proxy:
