---
# Huginn is a system for building agents that perform automated tasks for you online. They can read the web, watch for events, and take actions on your behalf. Huginn's Agents create and consume events, propagating them along a directed graph. Think of it as a hackable version of IFTTT or Zapier on your own server. You always know who has your data. You do.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  huginn-db-data:
  huginn-db-config:
  huginn-db-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  huginn-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  huginn:
    image: huginn/huginn
    container_name: huginn
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=huginn-db
      - HUGINN_DATABASE_NAME=${HUGINNDB_DB?HUGINNDB_DB Variable not set}
      - HUGINN_DATABASE_USERNAME=${HUGINNDB_USER?HUGINNDB_USER Variable not set}
      - HUGINN_DATABASE_PASSWORD=${HUGINNDB_PASS?HUGINNDB_PASS Variable not set}
    volumes:
      - huginn-log:/var/log
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.huginn-https.loadbalancer.server.port=3000
      - traefik.http.routers.huginn-https.entrypoints=https
      - traefik.http.routers.huginn-https.rule=Host(`${HUGINN_SUB?HUGINN_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.huginn-https.tls=true
      - traefik.http.routers.huginn-https.tls.certresolver=myresolver
      - traefik.http.routers.huginn-https.middlewares=authelia@docker
    networks:
      t2_proxy:
    depends_on:
      - huginn-db
  huginn-db:
    image: mariadb:latest
    container_name: huginn-db
    hostname: huginn-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${HUGINNDB_ROOT?HUGINNDB_ROOT Variable not set}
      MYSQL_DATABASE: ${HUGINNDB_DB?HUGINNDB_DB Variable not set}
      MYSQL_USER: ${HUGINNDB_USER?HUGINNDB_USER Variable not set}
      MYSQL_PASSWORD: ${HUGINNDB_PASS?HUGINNDB_PASS Variable not set}
    volumes:
      - huginn-db-data:/var/lib/mysql
      - huginn-db-log:/var/log
      - huginn-db-config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${HUGINNDB_ROOT?HUGINNDB_ROOT variable does not exist}"]
      interval: 10s
      timeout: 5s
      retries: 5