---
# Mylar3 is an automated Comic Book downloader (cbr/cbz) for use with NZB and torrents written in python. It supports SABnzbd, NZBGET, and many torrent clients.
version: "3.8"
networks:
  t2_proxy:
    external: true
  mylar3-config:
  mylar3-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:${MYLAR_VERSION}
    container_name: mylar3
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - mylar3-config:/config
      - mylar3-log:/var/log
      - ${COMICS_DIRECTORY}:/comics
      - ${MANGA_DIRECTORY}:/manga
      - ${DOWNLOAD_DIRECTORY}:/downloads
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.mylar-https.loadbalancer.server.port=8090
      - traefik.http.routers.mylar-https.entrypoints=https
      - traefik.http.routers.mylar-https.rule=Host(`${MYLAR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.mylar-https.tls=true
      - traefik.http.routers.mylar-https.tls.certresolver=myresolver
      - traefik.http.routers.mylar-https.middlewares=authelia@docker
    networks:
      t2_proxy:
