---
# Snippet Box is a simple self-hosted app for organizing your code snippets. It allows you to easily create, edit, browse and manage your snippets.
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  snippitbox:
    image: pawelmalak/snippet-box
    container_name: snippitbox
    volumes:
      - /var/data/snippitbox/data:/app/data
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.snippitbox-https.loadbalancer.server.port=5000
      - traefik.http.routers.snippitbox-https.entrypoints=https
      - traefik.http.routers.snippitbox-https.rule=Host(`${SNIPPITBOX_SUB?SNIPPITBOX_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.snippitbox-https.tls=true
      - traefik.http.routers.snippitbox-https.tls.certresolver=myresolver
      - traefik.http.routers.snippitbox-https.middlewares=authelia@docker
    networks:
      t2_proxy:
