version: '3'
# TODO: Everything
# https://github.com/itzg/mc-monitor/blob/master/examples/mc-monitor-prom/docker-compose.yml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    depends_on:
      - mc
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
volumes:
  mc-data: {}
  prometheus-tsdb: {}
  grafana-lib: {}
