---
# Lidarr is a music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new albums from your favorite artists
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  lidarr-config:
  lidarr-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - lidarr-config:/config
      - lidarr-log:/var/log
      - ${MUSIC_DIRECTORY}:/music
      - ${DOWNLOADS_DIRECTORY}:/downloads
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr-https.loadbalancer.server.port=8686
      - traefik.http.routers.lidarr-https.entrypoints=https
      - traefik.http.routers.lidarr-https.rule=Host(`${LIDARR_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.lidarr-https.tls=true
      - traefik.http.routers.lidarr-https.tls.certresolver=myresolver
      - traefik.http.routers.lidarr-https.middlewares=authelia@docker
    networks:
      t2_proxy:
