---
# Ghost is an open source, professional publishing platform built on a modern Node.js technology stack — designed for teams who need power, flexibility and performance.
# TO DO: Use standard user not root for mysql
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  ghost-db-data:
  ghost-db-config:
  ghost-db-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  ghost-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  ghost:
    image: ghost:4-alpine:$(GHOST_VERSION)
    container_name: ghost
    restart: ${RESTART_POLICY}
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ${GHOST_MYSQL_PASS}
      database__connection__database: ${GHOST_DATABASE_NAME}
      url: http://${GHOST_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      # NODE_ENV: development
    labels:
      - traefik.enable=true
      - traefik.http.services.ghost-https.loadbalancer.server.port=22300  # 2368?
      - traefik.http.routers.ghost-https.entrypoints=https
      - traefik.http.routers.ghost-https.rule=Host(`${GHOST_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.ghost-https.tls=true
      - traefik.http.routers.ghost-https.tls.certresolver=myresolver
      - traefik.http.routers.ghost-https.middlewares=authelia@docker
    volumes:
      - ghost-log:/var/log
    depends_on:
      - ghost-db
    networks:
      t2_proxy:
  ghost-db:
    image: mysql:${GHOST_MYSQL_VERSION}
    container_name: ghost-db
    hostname: ghost-db
    restart: ${RESTART_POLICY}
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_MYSQL_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${GHOST_MYSQL_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ghost-db-log:/var/log
      - ghost-db-data:/var/lib/mysql
      - ghost-db-config:/etc/mysql
