---
# Is a self-hosted monitoring tool like "Uptime Robot"
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    volumes:
      - /var/data/uptime-kuma/data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.services.kuma-https.loadbalancer.server.port=3001
      - traefik.http.routers.kuma-https.entrypoints=https
      - traefik.http.routers.kuma-https.rule=Host(`${KUMA_SUB?KUMA_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.kuma-https.tls=true
      - traefik.http.routers.kuma-https.tls.certresolver=myresolver
      - traefik.http.routers.kuma-https.middlewares=authelia@docker
    networks:
      t2_proxy:
