---
# OpenRA is an open source project that recreates and modernizes classic real time strategy games, like Red Alert, Command & Conquer, and Dune
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  openra-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  openra:
    image: rmoriz/openra:${OPENRA_VERSION}
    container_name: openra
    environment:
      - Name=${OPENRA_SERVER_NAME}
      - Mod=ra
      - ListenPort=1234
      - AdvertiseOnline=false
      - Password=${OPENRA_PASSWORD}
      - EnableSingleplayer=${OPENRA_SINGLE_PLAYER}
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.openra-https.loadbalancer.server.port=1234
      - traefik.http.routers.openra-https.entrypoints=https
      - traefik.http.routers.openra-https.rule=Host(`${OPENRA_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.openra-https.tls=true
      - traefik.http.routers.openra-https.tls.certresolver=myresolver
      - traefik.http.routers.openra-https.middlewares=authelia@docker
    volumes:
      - openra-log:/var/log
    networks:
      t2_proxy:
