---
# Medusa is an automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  medusa-config:
  medusa-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  medusa:
    image: lscr.io/linuxserver/medusa:${MEDUSA_VERSION}
    container_name: medusa
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - medusa-config:/config
      - medusa-log:/var/log
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - ${TV_DIRECTORY}:/tv
      - ${ANIME_DIRECTORY}:/anime
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.medusa-https.loadbalancer.server.port=8081
      - traefik.http.routers.medusa-https.entrypoints=https
      - traefik.http.routers.medusa-https.rule=Host(`${MEDUSA_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.medusa-https.tls=true
      - traefik.http.routers.medusa-https.tls.certresolver=myresolver
      - traefik.http.routers.medusa-https.middlewares=authelia@docker
    networks:
      t2_proxy:
