---
# exatorrent is Elegant BitTorrent Client written in Go. · It is Simple, easy to use, yet feature rich.
# To Do: check dir structure and map downloads and config seperately.
version: "3.8"
networks:
  t2_proxy:
    external: true
volumes:
  exatorrent-log:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  exatorrent:
    image: ghcr.io/varbhat/exatorrent:${EXATORRENT_VERSION}
    container_name: exatorrent
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/exa/exadir
      - exatorrent-log:/var/log
    ports:
      - ${EXATORRENT_PORT}:42069
    restart: ${RESTART_POLICY}
    labels:
      - traefik.enable=true
      - traefik.http.services.exatorrent-https.loadbalancer.server.port=5000
      - traefik.http.routers.exatorrent-https.entrypoints=https
      - traefik.http.routers.exatorrent-https.rule=Host(`${EXATORRENT_SUBDOMAIN}.${CLOUDFLARE_DOMAIN}`)
      - traefik.http.routers.exatorrent-https.tls=true
      - traefik.http.routers.exatorrent-https.tls.certresolver=myresolver
      - traefik.http.routers.exatorrent-https.middlewares=authelia@docker
    networks:
      t2_proxy:
