---
# exatorrent is Elegant BitTorrent Client written in Go. · It is Simple, easy to use, yet feature rich.
version: "3.8"
networks:
  t2_proxy:
    external: true
services:
  exatorrent:
    image: ghcr.io/varbhat/exatorrent:latest
    container_name: exatorrent
    volumes:
      - /mnt/exatorrent:/exa/exadir
    ports:
      - ${EXATORRENT_PORT?EXATORRENT_PORT Variable not set}:42069
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    labels:
      - traefik.enable=true
      - traefik.http.services.exatorrent-https.loadbalancer.server.port=5000
      - traefik.http.routers.exatorrent-https.entrypoints=https
      - traefik.http.routers.exatorrent-https.rule=Host(`${EXATORRENT_SUB?EXATORRENT_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
      - traefik.http.routers.exatorrent-https.tls=true
      - traefik.http.routers.exatorrent-https.tls.certresolver=myresolver
      - traefik.http.routers.exatorrent-https.middlewares=authelia@docker
    networks:
      t2_proxy:
