---
# Portus is a Self hosted registry
# TODO: Set IP on the registry not the app? Test what works etc
version: "3.8"
networks:
  t2_proxy:
    external: true
  pihole:
    driver: macvlan
    driver_opts:
      parent: ${ETHERNET_PORT?ETHERNET_PORT Variable not set}
    ipam:
      config:
        subnet: ${SUBNET_IP?SUBNET_IP Variable not set}
        gateway: ${GATEWAY_IP?GATEWAY_IP Variable not set}
        ip_range: ${SUBNET_RANGE?SUBNET_RANGE Variable not set}
services:
  portus:
    build: .
    image: opensuse/portus:development
    container_name: portus
    mac_address: e1:23:df:35:0d:5c
    command: bundle exec rails runner /srv/Portus/examples/development/compose/init.rb
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}
      - PORTUS_PUMA_HOST=0.0.0.0:3000
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      - PORTUS_SECURITY_CLAIR_SERVER=http://portus-clair:6060
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_DB_HOST=portus-db
      - PORTUS_DB_PASSWORD=${PORTUSDB_PASS?PORTUSDB_PASS Variable not set}
      - PORTUS_DB_POOL=5
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    labels:
        - traefik.enable=true
        - traefik.http.services.portus-https.loadbalancer.server.port=5000
        - traefik.http.routers.portus-https.entrypoints=https
        - traefik.http.routers.portus-https.rule=Host(`${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
        - traefik.http.routers.portus-https.tls=true
        - traefik.http.routers.portus-https.tls.certresolver=myresolver
#        - traefik.http.routers.portus-https.middlewares=authelia@docker
    volumes:
      - /var/data/portus/data:/srv/Portus
    depends_on:
      - portus-clair
      - portus-background
      - portus-db
      - portus-webpack
  networks:
    t2_proxy:
    portus:
      ipv4_address: ${PORTUS_IP?PORTUS_IP Variable not set}
  portus-background:
    image: opensuse/portus:development
    container_name: portus-background
    entrypoint: bundle exec rails runner /srv/Portus/bin/background.rb
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}
      - PORTUS_SECURITY_CLAIR_SERVER=http://portus-clair:6060
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_DB_HOST=portus-db
      - PORTUS_DB_PASSWORD=${PORTUSDB_PASS?PORTUSDB_PASS Variable not set}
      - PORTUS_DB_POOL=5
    volumes:
      - /var/data/portus/background:/srv/Portus
    depends_on:
    - portus-clair
    - portus-db
  portus-webpack:
    image: kkarczmarczyk/node-yarn:latest
    container_name: portus-webpack
    command: bash /srv/Portus/examples/development/compose/bootstrap-webpack
    working_dir: /srv/Portus
    volumes:
      - /var/data/portus/webpack:/srv/Portus
  portus-clair:
    image: quay.io/coreos/clair:v2.0.2
    container_name: portus-clair
    restart: ${RESTART_POLICY?RESTART_POLICY Variable not set}
    volumes:
      - /tmp:/tmp
      - /var/data/portus/clair/clair.yml:/clair.yml
    command: [-config, /clair.yml]
  portus-db:
    image: library/mariadb:10.0.23
    container_name: portus-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ${PORTUSDB_PASS?PORTUSDB_PASS Variable not set}
#  portus-postgres:
#    image: library/postgres:10-alpine
#    container_name: portus-postgres
#    environment:
#      POSTGRES_PASSWORD: ${PORTUSDB_PASS?PORTUSDB_PASS Variable not set}
  portus-registry:
    image: library/registry:2.6
    container_name: portus-registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/docker/registry/portus.crt
      REGISTRY_AUTH_TOKEN_REALM: http://$${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: $${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}:5000
      REGISTRY_AUTH_TOKEN_ISSUER: ${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://$${PORTUS_SUB?PORTUS_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/data/portus/registry:/registry_data
      - /var/data/portus/certificate/portus.crt:/etc/docker/registry/portus.crt:ro
    ports:
      - 5000:5000
      - 5001:5001
    labels:
        - traefik.enable=true
        - traefik.http.services.portus-registry-https.loadbalancer.server.port=5000
        - traefik.http.routers.portus-registry-https.entrypoints=https
        - traefik.http.routers.portus-registry-https.rule=Host(`${REGISTRY_SUB?REGISTRY_SUB Variable not set}.${DOMAIN?DOMAIN Variable not set}`)
        - traefik.http.routers.portus-registry-https.tls=true
        - traefik.http.routers.portus-registry-https.tls.certresolver=myresolver
#        - traefik.http.routers.portus-registry-https.middlewares=authelia@docker
    networks:
      t2_proxy:
    depends_on:
    - portus
